//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 03:30:18 PM IST 
//


package com.soapdemo.demo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SalesTerritoryRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SalesTerritoryRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="parent_territory_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="current_owner_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="employee_responsible_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="territory_team_id" type="{http://www.soapdemo.com/demo}list"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SalesTerritoryRequest", propOrder = {
    "id",
    "name",
    "level",
    "parentTerritoryId",
    "currentOwnerId",
    "employeeResponsibleId",
    "territoryTeamId"
})
public class SalesTerritoryRequest {

    protected long id;
    @XmlElement(required = true)
    protected String name;
    protected long level;
    @XmlElement(name = "parent_territory_id")
    protected long parentTerritoryId;
    @XmlElement(name = "current_owner_id")
    protected long currentOwnerId;
    @XmlElement(name = "employee_responsible_id")
    protected long employeeResponsibleId;
    @XmlList
    @XmlElement(name = "territory_team_id", type = Long.class)
    protected List<Long> territoryTeamId;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the level property.
     * 
     */
    public long getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     */
    public void setLevel(long value) {
        this.level = value;
    }

    /**
     * Gets the value of the parentTerritoryId property.
     * 
     */
    public long getParentTerritoryId() {
        return parentTerritoryId;
    }

    /**
     * Sets the value of the parentTerritoryId property.
     * 
     */
    public void setParentTerritoryId(long value) {
        this.parentTerritoryId = value;
    }

    /**
     * Gets the value of the currentOwnerId property.
     * 
     */
    public long getCurrentOwnerId() {
        return currentOwnerId;
    }

    /**
     * Sets the value of the currentOwnerId property.
     * 
     */
    public void setCurrentOwnerId(long value) {
        this.currentOwnerId = value;
    }

    /**
     * Gets the value of the employeeResponsibleId property.
     * 
     */
    public long getEmployeeResponsibleId() {
        return employeeResponsibleId;
    }

    /**
     * Sets the value of the employeeResponsibleId property.
     * 
     */
    public void setEmployeeResponsibleId(long value) {
        this.employeeResponsibleId = value;
    }

    /**
     * Gets the value of the territoryTeamId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the territoryTeamId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTerritoryTeamId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getTerritoryTeamId() {
        if (territoryTeamId == null) {
            territoryTeamId = new ArrayList<Long>();
        }
        return this.territoryTeamId;
    }

}
